### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by irene7c** [ydataai/ydata-profiling#1482]
### Current Behaviour

Traceback (most recent call last):
  File "/home/irene/dev/DRASTIC/.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_543254/2440055859.py", line 1, in <module>
    profile.to_file("your_report.html")
  File "/home/irene/dev/DRASTIC/.venv/lib/python3.9/site-packages/ydata_profiling/profile_report.py", line 355, in to_file
    data = self.to_html()
  File "/home/irene/dev/DRASTIC/.venv/lib/python3.9/site-packages/ydata_profiling/profile_report.py", line 470, in to_html
    return self.html
  File "/home/irene/dev/DRASTIC/.venv/lib/python3.9/site-packages/ydata_profiling/profile_report.py", line 277, in html
    self._html = self._render_html()
  File "/home/irene/dev/DRASTIC/.venv/lib/python3.9/site-packages/ydata_profiling/profile_report.py", line 385, in _render_html
    report = self.report
  File "/home/irene/dev/DRASTIC/.venv/lib/python3.9/site-packages/ydata_profiling/profile_report.py", line 271, in report
    self._report = get_report_structure(self.config, self.description_set)
  File "/home/irene/dev/DRASTIC/.venv/lib/python3.9/site-packages/ydata_profiling/profile_report.py", line 253, in description_set
    self._description_set = describe_df(
  File "/home/irene/dev/DRASTIC/.venv/lib/python3.9/site-packages/ydata_profiling/model/describe.py", line 130, in describe
    scatter_matrix[x][y] = progress(
  File "/home/irene/dev/DRASTIC/.venv/lib/python3.9/site-packages/ydata_profiling/utils/progress_bar.py", line 11, in inner
    ret = fn(*args, **kwargs)
  File "/home/irene/dev/DRASTIC/.venv/lib/python3.9/site-packages/ydata_profiling/model/pairwise.py", line 31, in get_scatter_plot
    return scatter_pairwise(config, df_temp[x], df_temp[y], x, y)
  File "/usr/lib/python3.9/contextlib.py", line 78, in inner
    with self._recreate_cm():
  File "/usr/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/irene/dev/DRASTIC/.venv/lib/python3.9/site-packages/ydata_profiling/visualisation/context.py", line 83, in manage_matplotlib_context
    deregister_matplotlib_converters()  # revert to original unit registries
  File "/home/irene/dev/DRASTIC/.venv/lib/python3.9/site-packages/pandas/plotting/_misc.py", line 151, in deregister
    <AxesSubplot: xlabel='B', ylabel='C'>,
  File "/home/irene/dev/DRASTIC/.venv/lib/python3.9/site-packages/pandas/plotting/_core.py", line 1947, in _get_plot_backend
  File "/home/irene/dev/DRASTIC/.venv/lib/python3.9/site-packages/pandas/plotting/_core.py", line 1877, in _load_backend
ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/irene/dev/DRASTIC/.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2120, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "/home/irene/dev/DRASTIC/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1435, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/irene/dev/DRASTIC/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1326, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/irene/dev/DRASTIC/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1173, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/home/irene/dev/DRASTIC/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1088, in format_exception_as_a_whole
    frames.append(self.format_record(record))
  File "/home/irene/dev/DRASTIC/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py", line 970, in format_record
    frame_info.lines, Colors, self.has_colors, lvals
  File "/home/irene/dev/DRASTIC/.venv/lib/python3.9/site-packages/IPython/core/ultratb.py", line 792, in lines
    return self._sd.lines
  File "/home/irene/dev/DRASTIC/.venv/lib/python3.9/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/irene/dev/DRASTIC/.venv/lib/python3.9/site-packages/stack_data/core.py", line 734, in lines
    pieces = self.included_pieces
  File "/home/irene/dev/DRASTIC/.venv/lib/python3.9/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/irene/dev/DRASTIC/.venv/lib/python3.9/site-packages/stack_data/core.py", line 681, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
  File "/home/irene/dev/DRASTIC/.venv/lib/python3.9/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/irene/dev/DRASTIC/.venv/lib/python3.9/site-packages/stack_data/core.py", line 660, in executing_piece
    return only(
  File "/home/irene/dev/DRASTIC/.venv/lib/python3.9/site-packages/executing/executing.py", line 116, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0

### Expected Behaviour

It should give me the profile in html 

### Data Description

I just test out the sample code from Quickstart in ydata-profiling website https://docs.profiling.ydata.ai/4.6/getting-started/quickstart/#using-inside-jupyter-notebooks

### Code that reproduces the bug

```Python
import numpy as np
import pandas as pd
from ydata_profiling import ProfileReport

df = pd.DataFrame(np.random.rand(100, 5), columns=["a", "b", "c", "d", "e"])

profile = ProfileReport(df, title="Pandas Profiling Report")

profile.to_file("your_report.html")
```

### pandas-profiling version

^4.6.0

### Dependencies

```Text
[tool.poetry]
name = "drastic"
version = "0.1.0"

[tool.poetry.dependencies]
python = "3.9.16"
scikit-learn = "^1.3.1"
plotly = "^5.17.0"
ydata-profiling = "^4.6.0"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.25.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

### OS

ubuntu

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by proselotis** [comment]
@irene7c 

For awareness, I am also encountering this error under similar build in a Jupyter notebook. The error occurs at the rendering HTML phase of creating the report.  What fixed my error is resorting to ydata_profiling version 4.5.1. I'm not sure what in the newer versions is causing this error.  

Code to install version specific
> pip install ydata-profiling[notebook]==4.5.1

**Comment by bovealexandre** [comment]
> Hi @irene7c ,
> 
> can you please share the following information, so we can make a better assessment of your request:
> 
>     * Python version being used
> 
>     * Your virtual environment installed packages
> 
> 
> Based on the error messages it seems like you are in an environment where for some reason your matplotlib package is corrupted.

@fabclmnt I have the same problem. My python is 3.11.6
and I'm not working on a virtual environment but in the same notebook I use seaborn and matplot and they work
