### ISSUE TITLE
 Getting requirements to build wheel did not run successfully.( ydata- profiling 4.6 error)

### ISSUE THREAD

**Issue by luch3x** [ydataai/ydata-profiling#1498]
### Current Behaviour

I was installing ydata-profiling from my files and I have this error

### Expected Behaviour

it should dowloaded

### Data Description

.

### Code that reproduces the bug

```Python
C:\Users\Usuario>pip install "C:\Users\Usuario\Downloads\ydata-profiling-develop"
Processing c:\users\usuario\downloads\ydata-profiling-develop
  Preparing metadata (setup.py) ... done
Requirement already satisfied: scipy<1.12,>=1.4.1 in c:\users\usuario\appdata\local\programs\python\python312\lib\site-packages (from ydata-profiling==0.0.dev0) (1.11.3)
Collecting pandas!=1.4.0,<2.1,>1.1 (from ydata-profiling==0.0.dev0)
  Using cached pandas-2.0.3.tar.gz (5.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting matplotlib<=3.7.3,>=3.2 (from ydata-profiling==0.0.dev0)
  Using cached matplotlib-3.7.3-cp312-cp312-win_amd64.whl.metadata (5.8 kB)
Requirement already satisfied: pydantic>=2 in c:\users\usuario\appdata\local\programs\python\python312\lib\site-packages (from ydata-profiling==0.0.dev0) (2.4.2)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in c:\users\usuario\appdata\local\programs\python\python312\lib\site-packages (from ydata-profiling==0.0.dev0) (6.0.1)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in c:\users\usuario\appdata\local\programs\python\python312\lib\site-packages (from ydata-profiling==0.0.dev0) (3.1.2)
Requirement already satisfied: visions==0.7.5 in c:\users\usuario\appdata\local\programs\python\python312\lib\site-packages (from visions[type_image_path]==0.7.5->ydata-profiling==0.0.dev0) (0.7.5)
Collecting numpy<1.26,>=1.16.0 (from ydata-profiling==0.0.dev0)
  Using cached numpy-1.25.2.tar.gz (10.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "C:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 994, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Users\Usuario\AppData\Local\Temp\pip-build-env-20xx808f\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\Usuario\AppData\Local\Temp\pip-build-env-20xx808f\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\Usuario\AppData\Local\Temp\pip-build-env-20xx808f\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### pandas-profiling version

4.6

### Dependencies

```Text
pandas 2.1.2
numpy 1.26.1
setuptools 68.2.2
pip 23.3.1
```

### OS

window 10 in the cdm

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by fabclmnt** [comment]
HI @luch3x ,
can you please share what is the python version that you are using? 

Based on the error it seems that you are using python 3.12. This is known issue and related with Numpy (https://github.com/pypa/pip/issues/12179)
