### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by abdrysdale** [ydataai/ydata-profiling#1618]
### Current Behaviour

Thanks for the great repository!

Currently fails on the import with

```python
import ydata_profilling
```

Resulting in:

```
Traceback (most recent call last):
  File "c:\Users\foo\test.py", line 9, in <module>
    import ydata_profiling
  File "C:\Users\foo\AppData\Local\pypoetry\Cache\virtualenvs\foo-nnQxNQNi-py3.12\Lib\site-packages\ydata_profiling\__init__.py", line 14, in <module>
    from ydata_profiling.compare_reports import compare  # isort:skip # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\foo\AppData\Local\pypoetry\Cache\virtualenvs\foo-nnQxNQNi-py3.12\Lib\site-packages\ydata_profiling\compare_reports.py", line 12, in <module>
    from ydata_profiling.profile_report import ProfileReport
  File "C:\Users\foo\AppData\Local\pypoetry\Cache\virtualenvs\foo-nnQxNQNi-py3.12\Lib\site-packages\ydata_profiling\profile_report.py", line 9, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

### Expected Behaviour

The library should be successfully imported.

### Data Description

Currently not using any data as it fails on the import.

### Code that reproduces the bug

```Python
import ydata_profiling.
```

### pandas-profiling version

4.8.3

### Dependencies

```Text
annotated-types==0.7.0
attrs==23.2.0
certifi==2024.7.4
charset-normalizer==3.3.2
colorama==0.4.6
contourpy==1.2.1
cycler==0.12.1
dacite==1.8.1
fonttools==4.53.1
h5py==3.11.0
htmlmin==0.1.12
idna==3.7
ImageHash==4.3.1
Jinja2==3.1.4
joblib==1.4.2
kiwisolver==1.4.5
llvmlite==0.43.0
MarkupSafe==2.1.5
matplotlib==3.8.4
multimethod==1.12
networkx==3.3
numba==0.60.0
numpy==1.26.4
packaging==24.1
pandas==2.2.2
patsy==0.5.6
phik==0.12.4
pillow==10.4.0
pydantic==2.8.2
pydantic_core==2.20.1
pydicom==2.4.4
pyparsing==3.1.2
python-dateutil==2.9.0.post0
pytz==2024.1
PyWavelets==1.6.0
PyYAML==6.0.1
requests==2.32.3
scipy==1.13.1
seaborn==0.13.2
setuptools==70.3.0
six==1.16.0
statsmodels==0.14.2
tqdm==4.66.4
typeguard==4.3.0
typing_extensions==4.12.2
tzdata==2024.1
urllib3==2.2.2
visions==0.7.6
wordcloud==1.9.3
ydata-profiling==4.8.3
```

### OS

Windows 11

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by abdrysdale** [comment]
This seems to be due to `setuptools` not being installed. A simple `pip install setuptools` or `poetry add setuptools` solves the issue.

**Comment by abdrysdale** [comment]
I've created a pull request for the fix which includes `setuptools` in the requirements.

However, it is worth noting that `pkg_resources` is being slowly depreciated in favor of [importlib.resources](https://docs.python.org/3/library/importlib.resources.html) and there is also a really handy [migration guide](https://importlib-resources.readthedocs.io/en/latest/migration.html) on the subject matter.

It's worth noting that `importlib.resources` only supports the following APIs:

- `pkg_resources.resource_filename()`
- `pkg_resources.resource_stream()`
- `pkg_resources.resource_string()`
- `pkg_resources.resource_listdir()`
- `pkg_resources.resource_isdir()`

so `importlib.resources` may not be an appropriate.

**Comment by jklaise** [comment]
The reason this happens is due to `setuptools` no longer being bundled with venvs from Python 3.12, I left a longer comment on the PR: https://github.com/ydataai/ydata-profiling/pull/1619#issuecomment-2478515087

**Comment by yaxxie-piramidal** [comment]
Seems like this still has not been fixed? are there any plans to fix this?

**Comment by abdrysdale** [comment]
> Seems like this still has not been fixed? are there any plans to fix this?

I don't think so. I [created a PR](https://github.com/ydataai/ydata-profiling/pull/1619) that fixed this but this was closed as @fabclmnt didn't believe the issue still exists.

I wrote tests that showcase this issue still being present but they still closed the PR.

For now, whenever I use ydata-profiling I just add setuptools as a requirement.

**Comment by waitasecant** [comment]
Denial is a river, similar issue occurred with [modis-tools](https://github.com/fraymio/modis-tools) raised the [issue](https://github.com/fraymio/modis-tools/issues/48) with them but they were kind enough to accept my [PR](https://github.com/fraymio/modis-tools/pull/49) but thanks for taking time and effort on this. 🙏🙌

**Comment by camillereaves** [comment]
The lines added in #1515 suppressed deprecation warnings but still imported `pkg_resources`:

```
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    import pkg_resources
```

This now requires pinning `setuptools <= 81` since newer releases of `setuptools` have entirely removed `pkg_resources`, causing the import to fail.

I've confirmed the library works with `setuptools <= 81` pinned.

**Comment by gsouf** [comment]
In case it saves time to other people: works on python 3.11. Broken on 3.12+
Took me over 1 hour to figure out it was not a problem from my env but from this package.

**Comment by FY-Han** [comment]
python -m pip install "setuptools==78.1.1" could fix

**Comment by abdrysdale** [comment]
@fabclmnt is there enough evidence in this issue to convince you that `setuptools` should be added as a requirement?

**Comment by andy3092** [comment]
I found that pkg_resources is deprecated from setuptools and has been and removed from version 82.0. So pin setuptools to  <82. See the release notes for setuptools https://setuptools.pypa.io/en/latest/history.html

**Comment by Connor56** [comment]
> python -m pip install "setuptools==78.1.1" could fix

This works! Cheers.

**Comment by jbbqqf** [comment]
Hi! Triaging older issues — I think this is the same root cause as [#1816](https://github.com/Data-Centric-AI-Community/fg-data-profiling/issues/1816), which has a concrete reproducer and a fix in flight.

Short version: setuptools 81 (Aug 2025) removed `pkg_resources`. The pre-fix code in `src/data_profiling/profile_report.py:11` did `import pkg_resources` unconditionally, so any environment with modern setuptools crashes at `import data_profiling` time with `ModuleNotFoundError: No module named 'pkg_resources'`. PR [#1847](https://github.com/Data-Centric-AI-Community/fg-data-profiling/pull/1847) (open against `develop`) replaces that with `importlib.metadata.version`, which has been in the stdlib since Python 3.8 and is therefore always available given the `>=3.10` floor in `pyproject.toml`.

Workaround until #1847 lands:
```bash
pip install 'setuptools<81'
```

If you agree, feel free to close in favour of #1816, or follow #1847 for the fix.

(Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the cross-link was verified manually against the current `develop` branch.)

**Comment by Mohammed-Gamal** [comment]
Installing a lower version of `setuptools` should fix the issue; the following version worked for me:

```Python
pip install 'setuptools<=80.10.2'
```
